default : &DEFAULT

  # General
  verbose: True 
  device: 'cuda' 
  

  # Diffusion
  diff:
    noise_steps: 1000
    beta_start:  0.0001
    beta_end:    0.02

  # Model
  unet:
    input_channels: 3
    output_channels: 3
    time_emb: 128
    

  # Optimizer
  opt:
    epochs: 1000
    lr: 0.0003
    eps: 0.00001
    weight_decay: 0.01

    scheduler_T_max: 500 # For cosine only, typically take n_epochs
    scheduler_patience: 100 # For ReduceLROnPlateau only
    scheduler: 'OneCycleLR' # Or 'CosineAnnealingLR' OR 'ReduceLROnPlateau'
    step_size: 100
    gamma: 0.5
    precision_schedule: None
    

  # Dataset related
  data:
    folder: '../Data/real_lenses_dataset/non_lenses' #'../Data/npy_lenses-20240731T044737Z-001/npy_lenses/'
    batch_size: 256
    image_size: 64
    train_test_splt: 0.9
    plot_freq: 50
    eval_freq: 100
    shuffle: True
    num_classes: None
    mean: [0.06814773380756378, 0.21582692861557007, 0.4182431399822235]
    std: [0.16798585653305054, 0.5532506108283997, 1.1966736316680908]

  